### ISSUE TITLE
How can I set global shortcuts to play/pause and like/dislike buttons?

### ISSUE THREAD

**Issue by kuntashov** [dedpnd/yaradio-yamusic#1]
Thanks for the app!

Is there any way to set up global shortcuts for items of tray menu?
It is the main feature that web app can't support but desktop app can.

**Comment by dedpnd** [comment]
@kuntashov Thanks for using my app!
Yes, there is such a possibility. I planned to add it in the next versions.

**Comment by kuntashov** [comment]
I've hardcoded hotkeys for myself by now, see https://github.com/kuntashov/yaradio-yamusic/commit/6d09772dae3b6e10dd781df72da531d689900b16 

Some of my hotkeys, e.g. MediaStop for next track action, looks really confusing, but it depends on my hardware keys )
