### ISSUE TITLE
Yandex blocked the app?

### ISSUE THREAD

**Issue by kuntashov** [dedpnd/yaradio-yamusic#13]
Just tried to switch from Radio to Music and got this:

![Screenshot_20200423_173130](https://user-images.githubusercontent.com/1042299/80106504-ffb11d80-858a-11ea-9aed-81ff6de04281.png)

Since then the app don't work.

I use Linux Mint + xfce windows manager (if it matters).

**Comment by kuntashov** [comment]
Release https://github.com/dedpnd/yaradio-yamusic/releases/tag/v.0.3.6 works well.

**Comment by dedpnd** [comment]
Thank You for your quick issue =) 
I'm already preparing a new release.
