### ISSUE TITLE
Using the back/forward mouse click stops the song that is currently playing

### ISSUE THREAD

**Issue by Mikey1993** [dedpnd/yaradio-yamusic#14]
**Edit: 
Please look for a possible solution proposed down below in my comment.**

Reproduce STR:
1) Start a playlist on your home screen (Let's say the playlist of the day)
2) While a song from that playlist is playing, enter to the playlist page by clicking on the name of the playlist.
3) Song is still playing fine.
4) Go back to the main page by clicking the back mouse button.
5) The whole page refreshes and the song **STOPS**.

This is very annoying, as you don't expect the song to stop while navigating.
The issue was reproduced with the new v.0.4.0 version.

Can this be fixed?
Thanks!

**Comment by dedpnd** [comment]
Thanks for issue.
This is the behavior of the new version electron 8.0.0, I'll try to fix it.

**Comment by Mikey1993** [comment]
**Edit:**
I was wrong, and the the workaround is not actually working for me anymore(?).
So it's a real bug that needs to be fixed..

<s>@dedpnd , Actually, it seems like the bug is only reproducible if you do an in place upgrade from the previous version v.0.3.6 to v.0.4.0
I'm not sure if every new version upgrade will have this type of an issue.

I managed to fix this issue by removing the program's folder, which resides in `%AppData%\Yandex.Music.App\`.

Note: Please be aware that removing this folder will reset ALL the settings of the app (equalizer settings, program screen size/position, login session), and you will have to login again through the app.

You can close this issue if you'd like.
Cheers.
<s>

**Comment by Mikey1993** [comment]
@dedpnd , looks like it's not working for me, and I am not sure if it ever worked for me back then - I might have used an older version all this time without even realizing it, so looks like this bug should be looked at...

**Comment by dedpnd** [comment]
@Mikey1993, "electron-builder" must exclude it. Let me know if this doesn't work
