### ISSUE TITLE
What about bitrate

### ISSUE THREAD

**Issue by SlimRG** [dedpnd/yaradio-yamusic#15]
Is it like with free substriction or like with paid substriction

**Comment by kuntashov** [comment]
Free Yandex.Music streams at 192 kbps bitrate.
On paid subscriptions (ie "Яндекс.Плюс") you could get 320 kbps bitrate by turning on HQ in top-right corner of player:

![Screenshot_20200523_212948](https://user-images.githubusercontent.com/1042299/82736666-91ec4300-9d3c-11ea-8615-92e724a5877f.png)

But real bitrate depends on particular track/album, sometimes you could get 192 kbps with HQ turned on - see https://roem.ru/02-02-2016/218250/music-yandex-hifi/ (only in Russian, sorry).
