### ISSUE TITLE
Please add "go to home page" action on "Radio" and "Music" buttons

### ISSUE THREAD

**Issue by user9931** [dedpnd/yaradio-yamusic#28]
It seems very intuitive when clicking on  big "Radio" or "Music" to open home page of a service (on Radio its usefulness may be controversial but on Music its very helpful). But thouse buttons do nothing.. 

![yamusic_buttons](https://user-images.githubusercontent.com/62539068/105625294-1b5a9480-5e39-11eb-91bd-b0a91b2e59a8.gif)

**Comment by dedpnd** [comment]
Hi.
I know about it. There is a vue-route it works right.
But I will try to take your wishes.

**Comment by dedpnd** [comment]
Added
