### ISSUE TITLE
Next song notification title

### ISSUE THREAD

**Issue by Kazun3500** [dedpnd/yaradio-yamusic#3]
now its like that
![изображение](https://user-images.githubusercontent.com/13629272/58703245-ae1b0580-83b0-11e9-965e-cfce8931d205.png)
I think it will be better to change notify-send to yaMusic.

**Comment by dedpnd** [comment]
This setting is not present in "node-notifier". I found it in the source code, but for some reason the developer made it not customizable. I'll be watching for updates
