### ISSUE TITLE
Unable to use bluetooth actions such as prev/next/start/stop functions

### ISSUE THREAD

**Issue by Mikey1993** [dedpnd/yaradio-yamusic#37]
I have a Sony WH-1000XM2 Bluetooth headphones, and unfortunately it's not registering the actions on it.
It's working fine with every other program on my PC, but not with this.

Thanks in advance!

**Comment by dedpnd** [comment]
@Mikey1993 
In the last update, I made a mistake. Check that you have active hotkeys.
![image](https://user-images.githubusercontent.com/18037236/108983737-37ec2580-76a0-11eb-8d43-5ca7eac7529a.png)

**Comment by Mikey1993** [comment]
@dedpnd
It works now with the latest version, thanks!
