### ISSUE TITLE
Some office shortcuts keys does not works when YaMusic running

### ISSUE THREAD

**Issue by Kenty82** [dedpnd/yaradio-yamusic#42]
Hello!
Some office shortcuts keys does not works when YaMusic running.
For example, MS Outlook shortcut key "Ctrl + Q" (mark mail as a read) does not works.
![image](https://user-images.githubusercontent.com/45921714/109148215-63920d00-777f-11eb-9f4b-96eae26e8abd.png)

p.s. Thanks for app!

**Comment by dedpnd** [comment]
@Kenty82 Hi!
"Ctrl + Q" its Exit. Turn it up, it works :)

**Comment by dedpnd** [comment]
@Kenty82 Thank you for bug. I fixed it.
