### ISSUE TITLE
Application blocks side panel

### ISSUE THREAD

**Issue by hrueschwein** [dedpnd/yaradio-yamusic#43]
On tihs panel you can see text, music video and other songs from album for song and descriptions for podcasts. 

Screenshot from browser:
![image](https://user-images.githubusercontent.com/61470955/112015856-3f86d900-8b3d-11eb-9ede-44a71a2b633b.png)

Screenshot from app;
![image](https://user-images.githubusercontent.com/61470955/112015982-5af1e400-8b3d-11eb-8f45-9a10486851ab.png)

**Comment by dedpnd** [comment]
Fix it.
