### ISSUE TITLE
Cannot open on macOs 10.14.6

### ISSUE THREAD

**Issue by dosmakov** [dedpnd/yaradio-yamusic#5]
Steps to reproduce:

1. Download latest build - https://github.com/dedpnd/yaradio-yamusic/releases/download/v.0.3.5/Yandex.Music.App-darwin-x64.7z
2. Unarchive
3. open -a Yandex.Music.App.app
LSOpenURLsWithRole() failed for the application Yandex.Music.App-darwin-x64/Yandex.Music.App.app with error -10810.

**Comment by ruslan-matrix** [comment]
The same on macOS 10.13.6

**Comment by dedpnd** [comment]
@dosmakov @ruslan-matrix thx for issue. Try lattest release.
