### ISSUE TITLE
"Login" isn't working

### ISSUE THREAD

**Issue by Wangfire42** [dedpnd/yaradio-yamusic#56]
"Login" isn't working.  passport_auth look's like:
![image](https://user-images.githubusercontent.com/94972360/143244813-ed94a18a-b0fd-4d9b-978b-20059653dbff.png)
You may to add manually cookie integrating function.
Or sumbit the instruction how to do it.

**Comment by dedpnd** [comment]
Thanks for issue, i try resolve it

**Comment by dedpnd** [comment]
@Wangfire42 
You can give more information. What is your release ? OS?
I checked, the app is working correctly.
