### ISSUE TITLE
Yandex radio broke rewinding next track

### ISSUE THREAD

**Issue by iHastr** [dedpnd/yaradio-yamusic#61]
Hi! At the end of April 2022, Yandex Radio broke rewinding the next track, even on the official website. Maybe you can programmatically fix it so that the next track plays automatically as before? Thanks!

**Comment by iHastr** [comment]
А по-русски. Автор, если Вы ещё живой, не смогли бы пофиксить перемотку треков в разделе Я.Радио? Следующий трек перематывается и замолкает. Нужно вручную нажимать его воспроизведение каждый раз. Понимаю, что это сломано на стороне самого Яндекса, они ведь хотят вообще забить болт на Радио. Может можно как-то программно дать пенделя, чтобы следующий трек начал звучать автоматически, как было раньше? Ведь в мобильной версии яндекс музыки версии до 2022 года, где ещё был раздел "Радио" перемотка ещё (пока) работает. Всех благ вам!

**Comment by dedpnd** [comment]
@iHastr hi! I try fix it. Never have time )

**Comment by iHastr** [comment]
Thank you! I believe that you will succeed, my dear friend!

**Comment by iHastr** [comment]
Sorry, your project is no longer working. Yandex completely removed the Radio site. Need to update the app.
