### ISSUE TITLE
Yamusic show ad

### ISSUE THREAD

**Issue by shamanpomedor** [dedpnd/yaradio-yamusic#62]
Since the last few days app has been constantly showing video ads, although there has never been such a problem before
![Снимок экрана (368)](https://user-images.githubusercontent.com/106553279/171045419-b217d020-5e0d-4dce-98c3-520f045b7e0c.png)

**Comment by DmitriyPekar** [comment]
да нехватает блокировщика рекламы

**Comment by TechnicalNick** [comment]
Очень-очень!

**Comment by 1Deluks** [comment]
Да бог с ней с блокировкой, не хватает альтернативы для поддержки автора. 

Сделайте альтернативный сбор на яндекс деньги или киви. Глядишь дело лучше пойдет =).

Прекрасная программа. <3

**Comment by dedpnd** [comment]
Guys, I've updated the blocker a lot time ago. But ability to build releases is disabled in "Travis CI". I'm trying to figure out how to get around this ban.
