### ISSUE TITLE
Cant hide to tray in latest release (v0.3.5)

### ISSUE THREAD

**Issue by kuntashov** [dedpnd/yaradio-yamusic#7]
Switched to v0.3.5 from my custom build and found that cant minimize app to tray anymore.
In previous version click on tray icon makes app to hide to tray.

"Show app" item in tray menu allows activate window, but cant hide it.

It is will be better to minimize app to tray on close app button or modify "Show app" item in tray menu to "Show/hide app to tray".

Tested on Linux Mint 17.3 Rosa Xfce edition

**Comment by dedpnd** [comment]
@kuntashov thanx for pull request, need test
