### ISSUE TITLE
Setting to specify where to show next song popup

### ISSUE THREAD

**Issue by kuntashov** [dedpnd/yaradio-yamusic#8]
Notifications are cool feature but by now it appear on top right, and it's very distracting for me.
I'd like if notification will be shown on bottom right.
It would be cool to have setting to specify where to show notification popup.

**Comment by dedpnd** [comment]
This setting is not present in "node-notifier". Try searching for this setting in your system's notification center

**Comment by kuntashov** [comment]
> This setting is not present in "node-notifier". Try searching for this setting in your system's notification center

Thanks. Found that on my Linux Mint Xfce Edition notification placement can be set globally via `xfce4-notifyd-config` app, but it works immediatly for all apps that uses notifications.
